/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as AppWorkspacesRouteImport } from './routes/_app/workspaces'
import { Route as ApiCliConfigRouteImport } from './routes/api/cli/config'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AppWorkspaceSlugRouteImport } from './routes/_app/workspace.$slug'
import { Route as AppUserSettingsRouteImport } from './routes/_app/user.settings'
import { Route as ApiCliAuthConfigRouteImport } from './routes/api/cli/auth/config'
import { Route as AppWorkspaceSlugAdminRouteRouteImport } from './routes/_app/workspace.$slug.admin/route'
import { Route as AppWorkspaceSlugAppRouteRouteImport } from './routes/_app/workspace.$slug._app/route'
import { Route as AppWorkspaceSlugAppIndexRouteImport } from './routes/_app/workspace.$slug._app/index'
import { Route as AppWorkspaceSlugAdminSettingsRouteImport } from './routes/_app/workspace.$slug.admin/settings'
import { Route as AppWorkspaceSlugAdminRevisionFilesRouteImport } from './routes/_app/workspace.$slug.admin/revision-files'
import { Route as AppWorkspaceSlugAdminModelsRouteImport } from './routes/_app/workspace.$slug.admin/models'
import { Route as AppWorkspaceSlugAdminMembersRouteImport } from './routes/_app/workspace.$slug.admin/members'
import { Route as AppWorkspaceSlugAdminExecutorRouteImport } from './routes/_app/workspace.$slug.admin/executor'
import { Route as AppWorkspaceSlugAdminEditorRouteImport } from './routes/_app/workspace.$slug.admin/editor'
import { Route as AppWorkspaceSlugAdminCredentialsRouteImport } from './routes/_app/workspace.$slug.admin/credentials'
import { Route as AppWorkspaceSlugAppPlaygroundRouteImport } from './routes/_app/workspace.$slug._app/playground'
import { Route as AppWorkspaceSlugAppChatIndexRouteImport } from './routes/_app/workspace.$slug._app/chat.index'
import { Route as AppWorkspaceSlugAppChatChatIdRouteImport } from './routes/_app/workspace.$slug._app/chat.$chatId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const ApiCliConfigRoute = ApiCliConfigRouteImport.update({
  id: '/api/cli/config',
  path: '/api/cli/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceSlugRoute = AppWorkspaceSlugRouteImport.update({
  id: '/workspace/$slug',
  path: '/workspace/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppUserSettingsRoute = AppUserSettingsRouteImport.update({
  id: '/user/settings',
  path: '/user/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiCliAuthConfigRoute = ApiCliAuthConfigRouteImport.update({
  id: '/api/cli/auth/config',
  path: '/api/cli/auth/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceSlugAdminRouteRoute =
  AppWorkspaceSlugAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugAppRouteRoute =
  AppWorkspaceSlugAppRouteRouteImport.update({
    id: '/_app',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugAppIndexRoute =
  AppWorkspaceSlugAppIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceSlugAppRouteRoute,
  } as any)
const AppWorkspaceSlugAdminSettingsRoute =
  AppWorkspaceSlugAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceSlugAdminRouteRoute,
  } as any)
const AppWorkspaceSlugAdminRevisionFilesRoute =
  AppWorkspaceSlugAdminRevisionFilesRouteImport.update({
    id: '/revision-files',
    path: '/revision-files',
    getParentRoute: () => AppWorkspaceSlugAdminRouteRoute,
  } as any)
const AppWorkspaceSlugAdminModelsRoute =
  AppWorkspaceSlugAdminModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => AppWorkspaceSlugAdminRouteRoute,
  } as any)
const AppWorkspaceSlugAdminMembersRoute =
  AppWorkspaceSlugAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppWorkspaceSlugAdminRouteRoute,
  } as any)
const AppWorkspaceSlugAdminExecutorRoute =
  AppWorkspaceSlugAdminExecutorRouteImport.update({
    id: '/executor',
    path: '/executor',
    getParentRoute: () => AppWorkspaceSlugAdminRouteRoute,
  } as any)
const AppWorkspaceSlugAdminEditorRoute =
  AppWorkspaceSlugAdminEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AppWorkspaceSlugAdminRouteRoute,
  } as any)
const AppWorkspaceSlugAdminCredentialsRoute =
  AppWorkspaceSlugAdminCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AppWorkspaceSlugAdminRouteRoute,
  } as any)
const AppWorkspaceSlugAppPlaygroundRoute =
  AppWorkspaceSlugAppPlaygroundRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => AppWorkspaceSlugAppRouteRoute,
  } as any)
const AppWorkspaceSlugAppChatIndexRoute =
  AppWorkspaceSlugAppChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => AppWorkspaceSlugAppRouteRoute,
  } as any)
const AppWorkspaceSlugAppChatChatIdRoute =
  AppWorkspaceSlugAppChatChatIdRouteImport.update({
    id: '/chat/$chatId',
    path: '/chat/$chatId',
    getParentRoute: () => AppWorkspaceSlugAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/user/settings': typeof AppUserSettingsRoute
  '/workspace/$slug': typeof AppWorkspaceSlugAppRouteRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/cli/config': typeof ApiCliConfigRoute
  '/workspace/$slug/admin': typeof AppWorkspaceSlugAdminRouteRouteWithChildren
  '/api/cli/auth/config': typeof ApiCliAuthConfigRoute
  '/workspace/$slug/playground': typeof AppWorkspaceSlugAppPlaygroundRoute
  '/workspace/$slug/admin/credentials': typeof AppWorkspaceSlugAdminCredentialsRoute
  '/workspace/$slug/admin/editor': typeof AppWorkspaceSlugAdminEditorRoute
  '/workspace/$slug/admin/executor': typeof AppWorkspaceSlugAdminExecutorRoute
  '/workspace/$slug/admin/members': typeof AppWorkspaceSlugAdminMembersRoute
  '/workspace/$slug/admin/models': typeof AppWorkspaceSlugAdminModelsRoute
  '/workspace/$slug/admin/revision-files': typeof AppWorkspaceSlugAdminRevisionFilesRoute
  '/workspace/$slug/admin/settings': typeof AppWorkspaceSlugAdminSettingsRoute
  '/workspace/$slug/': typeof AppWorkspaceSlugAppIndexRoute
  '/workspace/$slug/chat/$chatId': typeof AppWorkspaceSlugAppChatChatIdRoute
  '/workspace/$slug/chat/': typeof AppWorkspaceSlugAppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/user/settings': typeof AppUserSettingsRoute
  '/workspace/$slug': typeof AppWorkspaceSlugAppIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/cli/config': typeof ApiCliConfigRoute
  '/workspace/$slug/admin': typeof AppWorkspaceSlugAdminRouteRouteWithChildren
  '/api/cli/auth/config': typeof ApiCliAuthConfigRoute
  '/workspace/$slug/playground': typeof AppWorkspaceSlugAppPlaygroundRoute
  '/workspace/$slug/admin/credentials': typeof AppWorkspaceSlugAdminCredentialsRoute
  '/workspace/$slug/admin/editor': typeof AppWorkspaceSlugAdminEditorRoute
  '/workspace/$slug/admin/executor': typeof AppWorkspaceSlugAdminExecutorRoute
  '/workspace/$slug/admin/members': typeof AppWorkspaceSlugAdminMembersRoute
  '/workspace/$slug/admin/models': typeof AppWorkspaceSlugAdminModelsRoute
  '/workspace/$slug/admin/revision-files': typeof AppWorkspaceSlugAdminRevisionFilesRoute
  '/workspace/$slug/admin/settings': typeof AppWorkspaceSlugAdminSettingsRoute
  '/workspace/$slug/chat/$chatId': typeof AppWorkspaceSlugAppChatChatIdRoute
  '/workspace/$slug/chat': typeof AppWorkspaceSlugAppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/workspaces': typeof AppWorkspacesRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_app/user/settings': typeof AppUserSettingsRoute
  '/_app/workspace/$slug': typeof AppWorkspaceSlugRouteWithChildren
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/cli/config': typeof ApiCliConfigRoute
  '/_app/workspace/$slug/_app': typeof AppWorkspaceSlugAppRouteRouteWithChildren
  '/_app/workspace/$slug/admin': typeof AppWorkspaceSlugAdminRouteRouteWithChildren
  '/api/cli/auth/config': typeof ApiCliAuthConfigRoute
  '/_app/workspace/$slug/_app/playground': typeof AppWorkspaceSlugAppPlaygroundRoute
  '/_app/workspace/$slug/admin/credentials': typeof AppWorkspaceSlugAdminCredentialsRoute
  '/_app/workspace/$slug/admin/editor': typeof AppWorkspaceSlugAdminEditorRoute
  '/_app/workspace/$slug/admin/executor': typeof AppWorkspaceSlugAdminExecutorRoute
  '/_app/workspace/$slug/admin/members': typeof AppWorkspaceSlugAdminMembersRoute
  '/_app/workspace/$slug/admin/models': typeof AppWorkspaceSlugAdminModelsRoute
  '/_app/workspace/$slug/admin/revision-files': typeof AppWorkspaceSlugAdminRevisionFilesRoute
  '/_app/workspace/$slug/admin/settings': typeof AppWorkspaceSlugAdminSettingsRoute
  '/_app/workspace/$slug/_app/': typeof AppWorkspaceSlugAppIndexRoute
  '/_app/workspace/$slug/_app/chat/$chatId': typeof AppWorkspaceSlugAppChatChatIdRoute
  '/_app/workspace/$slug/_app/chat/': typeof AppWorkspaceSlugAppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspaces'
    | '/oauth/callback'
    | '/user/settings'
    | '/workspace/$slug'
    | '/api/auth/callback'
    | '/api/cli/config'
    | '/workspace/$slug/admin'
    | '/api/cli/auth/config'
    | '/workspace/$slug/playground'
    | '/workspace/$slug/admin/credentials'
    | '/workspace/$slug/admin/editor'
    | '/workspace/$slug/admin/executor'
    | '/workspace/$slug/admin/members'
    | '/workspace/$slug/admin/models'
    | '/workspace/$slug/admin/revision-files'
    | '/workspace/$slug/admin/settings'
    | '/workspace/$slug/'
    | '/workspace/$slug/chat/$chatId'
    | '/workspace/$slug/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspaces'
    | '/oauth/callback'
    | '/user/settings'
    | '/workspace/$slug'
    | '/api/auth/callback'
    | '/api/cli/config'
    | '/workspace/$slug/admin'
    | '/api/cli/auth/config'
    | '/workspace/$slug/playground'
    | '/workspace/$slug/admin/credentials'
    | '/workspace/$slug/admin/editor'
    | '/workspace/$slug/admin/executor'
    | '/workspace/$slug/admin/members'
    | '/workspace/$slug/admin/models'
    | '/workspace/$slug/admin/revision-files'
    | '/workspace/$slug/admin/settings'
    | '/workspace/$slug/chat/$chatId'
    | '/workspace/$slug/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/workspaces'
    | '/oauth/callback'
    | '/_app/user/settings'
    | '/_app/workspace/$slug'
    | '/api/auth/callback'
    | '/api/cli/config'
    | '/_app/workspace/$slug/_app'
    | '/_app/workspace/$slug/admin'
    | '/api/cli/auth/config'
    | '/_app/workspace/$slug/_app/playground'
    | '/_app/workspace/$slug/admin/credentials'
    | '/_app/workspace/$slug/admin/editor'
    | '/_app/workspace/$slug/admin/executor'
    | '/_app/workspace/$slug/admin/members'
    | '/_app/workspace/$slug/admin/models'
    | '/_app/workspace/$slug/admin/revision-files'
    | '/_app/workspace/$slug/admin/settings'
    | '/_app/workspace/$slug/_app/'
    | '/_app/workspace/$slug/_app/chat/$chatId'
    | '/_app/workspace/$slug/_app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OauthCallbackRoute: typeof OauthCallbackRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiCliConfigRoute: typeof ApiCliConfigRoute
  ApiCliAuthConfigRoute: typeof ApiCliAuthConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/cli/config': {
      id: '/api/cli/config'
      path: '/api/cli/config'
      fullPath: '/api/cli/config'
      preLoaderRoute: typeof ApiCliConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace/$slug': {
      id: '/_app/workspace/$slug'
      path: '/workspace/$slug'
      fullPath: '/workspace/$slug'
      preLoaderRoute: typeof AppWorkspaceSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user/settings': {
      id: '/_app/user/settings'
      path: '/user/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof AppUserSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/cli/auth/config': {
      id: '/api/cli/auth/config'
      path: '/api/cli/auth/config'
      fullPath: '/api/cli/auth/config'
      preLoaderRoute: typeof ApiCliAuthConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace/$slug/admin': {
      id: '/_app/workspace/$slug/admin'
      path: '/admin'
      fullPath: '/workspace/$slug/admin'
      preLoaderRoute: typeof AppWorkspaceSlugAdminRouteRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/workspace/$slug/_app': {
      id: '/_app/workspace/$slug/_app'
      path: ''
      fullPath: '/workspace/$slug'
      preLoaderRoute: typeof AppWorkspaceSlugAppRouteRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/_app/workspace/$slug/_app/': {
      id: '/_app/workspace/$slug/_app/'
      path: '/'
      fullPath: '/workspace/$slug/'
      preLoaderRoute: typeof AppWorkspaceSlugAppIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugAppRouteRoute
    }
    '/_app/workspace/$slug/admin/settings': {
      id: '/_app/workspace/$slug/admin/settings'
      path: '/settings'
      fullPath: '/workspace/$slug/admin/settings'
      preLoaderRoute: typeof AppWorkspaceSlugAdminSettingsRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRouteRoute
    }
    '/_app/workspace/$slug/admin/revision-files': {
      id: '/_app/workspace/$slug/admin/revision-files'
      path: '/revision-files'
      fullPath: '/workspace/$slug/admin/revision-files'
      preLoaderRoute: typeof AppWorkspaceSlugAdminRevisionFilesRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRouteRoute
    }
    '/_app/workspace/$slug/admin/models': {
      id: '/_app/workspace/$slug/admin/models'
      path: '/models'
      fullPath: '/workspace/$slug/admin/models'
      preLoaderRoute: typeof AppWorkspaceSlugAdminModelsRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRouteRoute
    }
    '/_app/workspace/$slug/admin/members': {
      id: '/_app/workspace/$slug/admin/members'
      path: '/members'
      fullPath: '/workspace/$slug/admin/members'
      preLoaderRoute: typeof AppWorkspaceSlugAdminMembersRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRouteRoute
    }
    '/_app/workspace/$slug/admin/executor': {
      id: '/_app/workspace/$slug/admin/executor'
      path: '/executor'
      fullPath: '/workspace/$slug/admin/executor'
      preLoaderRoute: typeof AppWorkspaceSlugAdminExecutorRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRouteRoute
    }
    '/_app/workspace/$slug/admin/editor': {
      id: '/_app/workspace/$slug/admin/editor'
      path: '/editor'
      fullPath: '/workspace/$slug/admin/editor'
      preLoaderRoute: typeof AppWorkspaceSlugAdminEditorRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRouteRoute
    }
    '/_app/workspace/$slug/admin/credentials': {
      id: '/_app/workspace/$slug/admin/credentials'
      path: '/credentials'
      fullPath: '/workspace/$slug/admin/credentials'
      preLoaderRoute: typeof AppWorkspaceSlugAdminCredentialsRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRouteRoute
    }
    '/_app/workspace/$slug/_app/playground': {
      id: '/_app/workspace/$slug/_app/playground'
      path: '/playground'
      fullPath: '/workspace/$slug/playground'
      preLoaderRoute: typeof AppWorkspaceSlugAppPlaygroundRouteImport
      parentRoute: typeof AppWorkspaceSlugAppRouteRoute
    }
    '/_app/workspace/$slug/_app/chat/': {
      id: '/_app/workspace/$slug/_app/chat/'
      path: '/chat'
      fullPath: '/workspace/$slug/chat/'
      preLoaderRoute: typeof AppWorkspaceSlugAppChatIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugAppRouteRoute
    }
    '/_app/workspace/$slug/_app/chat/$chatId': {
      id: '/_app/workspace/$slug/_app/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/workspace/$slug/chat/$chatId'
      preLoaderRoute: typeof AppWorkspaceSlugAppChatChatIdRouteImport
      parentRoute: typeof AppWorkspaceSlugAppRouteRoute
    }
  }
}

interface AppWorkspaceSlugAppRouteRouteChildren {
  AppWorkspaceSlugAppPlaygroundRoute: typeof AppWorkspaceSlugAppPlaygroundRoute
  AppWorkspaceSlugAppIndexRoute: typeof AppWorkspaceSlugAppIndexRoute
  AppWorkspaceSlugAppChatChatIdRoute: typeof AppWorkspaceSlugAppChatChatIdRoute
  AppWorkspaceSlugAppChatIndexRoute: typeof AppWorkspaceSlugAppChatIndexRoute
}

const AppWorkspaceSlugAppRouteRouteChildren: AppWorkspaceSlugAppRouteRouteChildren =
  {
    AppWorkspaceSlugAppPlaygroundRoute: AppWorkspaceSlugAppPlaygroundRoute,
    AppWorkspaceSlugAppIndexRoute: AppWorkspaceSlugAppIndexRoute,
    AppWorkspaceSlugAppChatChatIdRoute: AppWorkspaceSlugAppChatChatIdRoute,
    AppWorkspaceSlugAppChatIndexRoute: AppWorkspaceSlugAppChatIndexRoute,
  }

const AppWorkspaceSlugAppRouteRouteWithChildren =
  AppWorkspaceSlugAppRouteRoute._addFileChildren(
    AppWorkspaceSlugAppRouteRouteChildren,
  )

interface AppWorkspaceSlugAdminRouteRouteChildren {
  AppWorkspaceSlugAdminCredentialsRoute: typeof AppWorkspaceSlugAdminCredentialsRoute
  AppWorkspaceSlugAdminEditorRoute: typeof AppWorkspaceSlugAdminEditorRoute
  AppWorkspaceSlugAdminExecutorRoute: typeof AppWorkspaceSlugAdminExecutorRoute
  AppWorkspaceSlugAdminMembersRoute: typeof AppWorkspaceSlugAdminMembersRoute
  AppWorkspaceSlugAdminModelsRoute: typeof AppWorkspaceSlugAdminModelsRoute
  AppWorkspaceSlugAdminRevisionFilesRoute: typeof AppWorkspaceSlugAdminRevisionFilesRoute
  AppWorkspaceSlugAdminSettingsRoute: typeof AppWorkspaceSlugAdminSettingsRoute
}

const AppWorkspaceSlugAdminRouteRouteChildren: AppWorkspaceSlugAdminRouteRouteChildren =
  {
    AppWorkspaceSlugAdminCredentialsRoute:
      AppWorkspaceSlugAdminCredentialsRoute,
    AppWorkspaceSlugAdminEditorRoute: AppWorkspaceSlugAdminEditorRoute,
    AppWorkspaceSlugAdminExecutorRoute: AppWorkspaceSlugAdminExecutorRoute,
    AppWorkspaceSlugAdminMembersRoute: AppWorkspaceSlugAdminMembersRoute,
    AppWorkspaceSlugAdminModelsRoute: AppWorkspaceSlugAdminModelsRoute,
    AppWorkspaceSlugAdminRevisionFilesRoute:
      AppWorkspaceSlugAdminRevisionFilesRoute,
    AppWorkspaceSlugAdminSettingsRoute: AppWorkspaceSlugAdminSettingsRoute,
  }

const AppWorkspaceSlugAdminRouteRouteWithChildren =
  AppWorkspaceSlugAdminRouteRoute._addFileChildren(
    AppWorkspaceSlugAdminRouteRouteChildren,
  )

interface AppWorkspaceSlugRouteChildren {
  AppWorkspaceSlugAppRouteRoute: typeof AppWorkspaceSlugAppRouteRouteWithChildren
  AppWorkspaceSlugAdminRouteRoute: typeof AppWorkspaceSlugAdminRouteRouteWithChildren
}

const AppWorkspaceSlugRouteChildren: AppWorkspaceSlugRouteChildren = {
  AppWorkspaceSlugAppRouteRoute: AppWorkspaceSlugAppRouteRouteWithChildren,
  AppWorkspaceSlugAdminRouteRoute: AppWorkspaceSlugAdminRouteRouteWithChildren,
}

const AppWorkspaceSlugRouteWithChildren =
  AppWorkspaceSlugRoute._addFileChildren(AppWorkspaceSlugRouteChildren)

interface AppRouteChildren {
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppUserSettingsRoute: typeof AppUserSettingsRoute
  AppWorkspaceSlugRoute: typeof AppWorkspaceSlugRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppUserSettingsRoute: AppUserSettingsRoute,
  AppWorkspaceSlugRoute: AppWorkspaceSlugRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OauthCallbackRoute: OauthCallbackRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiCliConfigRoute: ApiCliConfigRoute,
  ApiCliAuthConfigRoute: ApiCliAuthConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
